---
kind: pipeline
type: docker
name: default

steps:
  - name: publish
    image: drone-bazelisk-ecr
    pull: never
    settings:
      target: :push_test
      tag: dev
      repository: drone-bazelisk-ecr-example
      registry:
        from_secret: ECR_REGISTRY
      access_key:
        from_secret: AWS_ACCESS_KEY_ID
      secret_key:
        from_secret: AWS_SECRET_ACCESS_KEY
